#cloud-config
disable_root: true
users:
  - name: ${username}
    groups: sudo
    shell: /bin/bash
    sudo: ['ALL=(ALL) NOPASSWD:ALL']
    ssh_authorized_keys:
      - ${ssh_public_key}
package_update: true
package_upgrade: false
packages: ${packages}
write_files:
  - path: /var/www/html/index.html
    content: |
      <html>
      <head>
      Hey, Netology
      </head>
      <body>
      <h1>I will be DevOps Engineer!</h1>
      </body>
      </html>
runcmd:
  - service nginx restart