#cloud-config
disable_root: true
users:
  - name: lesnykh
    groups: sudo
    shell: /bin/bash
    sudo: ['ALL=(ALL) NOPASSWD:ALL']
    ssh_authorized_keys:
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDEPo5w5gXf2bRSOfglLQeQMWCeBGR+OjDg30KkP8aTSusoGMij86K6SXZQcv/z3uBezbPAaHZxQ1EZUT/Mfxnqf9Jq2xYCTaP193fxDRgmn2cY30tW5XIFIZPt4nh627Uvc45WNQv2humNr4U6uMhpHZc4GSEsrWrj85T4hE29UDGCD1yb9/xDLOejDuQurSf3MXaPeeD0X5TogofYwW8MnEYrIFQ/rQEEJjtq/AvWJF2IjFICl+nD7s9XiZbh0FMXmkRRVLyA8+ekPU6QRS+hhLCWu83KNP/B+4PgokzJW8HiMHaeUEGVfxvB+r0vhgw4rVBQJm7ArAGi/MFJDxTZaM9S7Qc75P03HGcd5z2BIeKUkLzL/BNQ9AqJAog3XIfeFy2EYsSo3NOK3Zd5vtO1UOyJJ62Mcu+3lCCLnwZ2brHaPRcQIjE8qmMOY/ahumcsdjTUTJthWcEWWsLyhcBbNod2d/hArt1MUlFKIjYXDCUIsIOjaUsZpmJcUm870Os= lesnykh@debian